services:
  frontdoor:
    hostname: frontdoor
    image: lmello/ticket-window-frontdoor:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - kafka

  dashboard:
    hostname: dashboard
    image: lmello/ticket-window-dashboard:latest
    ports:
      - 8081:8080
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env

  attendant-1:
    hostname: attendant-1
    image: lmello/ticket-window-attendant:latest
    depends_on:
      - kafka
    env_file:
      - .env

  attendant-2:
    hostname: attendant-2
    image: lmello/ticket-window-attendant:latest
    depends_on:
      - kafka
    env_file:
      - .env

  attendant-3:
    hostname: attendant-3
    image: lmello/ticket-window-attendant:latest
    depends_on:
      - kafka
    env_file:
      - .env

  postgres:
    hostname: postgres
    image: postgres
    env_file:
      - .env

  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres:
